In [1]:
import pandas as pd

df = pd.read_csv('../data/wine_data.csv')
df

,Alcohol,Malic,Ash,Alcalinity,Magesium,Phenols,Flavanoids,Nonflavanoids,Proanthocyanins,Color,Hue,Dilution,Proline,class
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,0
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,0
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,0
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,0
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,2
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,2
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,2
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,2
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,2

In [2]:
from my_functions import create_feature_target, clf_eval

X_train, X_test, y_train, y_test = create_feature_target(df)

In [5]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

lda = LinearDiscriminantAnalysis()
lda.fit(X_train, y_train)
X_tn_lda = lda.transform(X_train)
X_te_lda = lda.transform(X_test)

In [6]:
print(lda.intercept_)

[-10.77460385  -4.05606805 -12.30592102]

In [7]:
print(lda.coef_)

[[ 2.02572132e+00 -1.16659694e-01  1.35458963e+00 -2.87901274e+00
  -2.56762600e-02 -2.75610923e+00  8.66259621e+00  9.35306011e-01
  -1.32272748e+00 -1.58395887e+00  2.20554380e-02  4.12128015e+00
   5.16432687e+00]
 [-1.52548694e+00 -1.06047787e+00 -1.50255310e+00  1.26859671e+00
   3.19703626e-03  2.23029233e-01  6.23886461e-01  1.91915773e-01
   7.59673715e-01 -1.53736528e+00  8.18724852e-01  1.12845517e-01
  -2.22073975e+00]
 [-1.72754227e-01  1.51371355e+00  5.16283028e-01  1.42339891e+00
   2.33236835e-02  2.66091208e+00 -1.00983473e+01 -1.25343186e+00
   4.22397201e-01  3.71031522e+00 -1.09577051e+00 -4.56343119e+00
  -2.62509579e+00]]

In [8]:
lda_columns = ['lda_comp1', 'lda_comp2']
X_tn_lda_df = pd.DataFrame(X_tn_lda, columns=lda_columns)
X_tn_lda_df['target'] = y_train.reset_index(drop=True)
X_tn_lda_df.head(5)

   lda_comp1  lda_comp2  target
0   3.573156   1.940189       2
1   0.854759  -2.081830       1
2   0.621737  -3.062345       1
3   4.807864   2.006387       2
4  -3.857976   0.149873       0

In [9]:
from sklearn.ensemble import RandomForestClassifier

clf_rf_lda = RandomForestClassifier(max_depth=2, random_state=0)
clf_rf_lda.fit(X_tn_lda, y_train)
pred_rf_lda = clf_rf_lda.predict(X_te_lda)

In [10]:
clf_eval(y_test, pred_rf_lda)

<evaluate>
accuracy: 1.0
precision: 1.0
recall: 1.0
f1: 1.0
============================================================
<confusion matrix>
 [[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]
============================================================
<class report>
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00         6

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36