In [1]:
import pandas as pd

df = pd.read_csv('../data/wine_data.csv')
df

,Alcohol,Malic,Ash,Alcalinity,Magesium,Phenols,Flavanoids,Nonflavanoids,Proanthocyanins,Color,Hue,Dilution,Proline,class
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,0
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,0
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,0
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,0
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,2
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,2
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,2
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,2
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,2

In [2]:
from my_functions import create_feature_target, clf_eval

X_train, X_test, y_train, y_test = create_feature_target(df)

In [3]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
pca.fit(X_train)
X_train_pca = pca.transform(X_train)
X_test_pca = pca.transform(X_test)

In [5]:
print(X_train_pca.shape)
print(X_test_pca.shape)

(142, 2)
(36, 2)

In [6]:
print(pca.singular_values_)

[26.09369    18.88432045]

In [7]:
print(pca.components_)

[[ 0.12959991 -0.24464064 -0.01018912 -0.24051579  0.12649451  0.38944115
   0.42757808 -0.30505669  0.30775255 -0.11027186  0.30710508  0.37636185
   0.2811085 ]
 [-0.49807323 -0.23168482 -0.31496874  0.02321825 -0.25841951 -0.1006849
  -0.02097952 -0.0399057  -0.06746036 -0.53087111  0.27161729  0.16071181
  -0.36547344]]

In [8]:
print(pca.explained_variance_)

[4.82894083 2.52920254]

In [9]:
print(pca.explained_variance_ratio_)

[0.36884109 0.19318394]

In [10]:
pca_columns = ['pca_comp1', 'pca_comp2']
X_train_pca_df = pd.DataFrame(X_train_pca, columns=pca_columns)
y_tn1 = y_test.reset_index(drop=True)
X_train_pca_df['target'] = y_tn1
X_train_pca_df.head(10)

   pca_comp1  pca_comp2  target
0  -2.178845  -1.072185     0.0
1  -1.808192   1.578223     2.0
2   1.098295   2.221243     1.0
3  -2.555847  -1.662104     0.0
4   1.856981   0.241573     1.0
5   2.582886  -1.376682     1.0
6   0.872876   2.256185     0.0
7  -0.418384   2.354157     2.0
8  -0.304977   2.276594     1.0
9   2.140825  -1.100529     1.0